services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: transport-express-backend
    restart: unless-stopped
    expose:
      - "4002"
    env_file:
      - ./backend.env
    networks:
      - transport-express
      - proxy-network

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: transport-express-frontend
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - transport-express
      - proxy-network

networks:
  transport-express:
    name: transport-express

  proxy-network:
    external: true
