export enum TrackingStatus {
  PENDING = 'pending',
  INFO_RECEIVED = 'info_received',
  CREATED = 'created',
  PICKED_UP = 'picked_up',
  IN_TRANSIT = 'in_transit',
  OUT_FOR_DELIVERY = 'out_for_delivery',
  DELIVERED = 'delivered',
  DELIVERY_FAILED = 'delivery_failed',
  RETURNING = 'returning',
  RETURNED = 'returned',
  CANCELLED = 'cancelled',
  NOT_FOUND = 'not_found',
  UNKNOWN = 'unknown',
}
